import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

// Read design-system.json
const designSystem = JSON.parse(
  readFileSync(join(rootDir, 'design-system.json'), 'utf-8')
);

let css = `/**
 * Design System CSS Variables
 * 
 * This file is AUTO-GENERATED from design-system.json.
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * To regenerate: npm run tokens:generate
 * 
 * CSS variables are like placeholders - you write "var(--color-blue-500)"
 * and it automatically uses the value from your design system.
 */

:root {
`;

// Helper function to convert kebab-case to CSS variable name
function toCSSVar(parts) {
  return `--${parts.join('-')}`;
}

// Map Figma font weight names to CSS numeric values
const fontWeightMap = {
  'Thin': 100,
  'ExtraLight': 200,
  'UltraLight': 200,
  'Light': 300,
  'Regular': 400,
  'Normal': 400,
  'Medium': 500,
  'SemiBold': 600,
  'DemiBold': 600,
  'Bold': 700,
  'ExtraBold': 800,
  'UltraBold': 800,
  'Black': 900,
  'Heavy': 900,
};

// Helper function to resolve $ref references
function resolveRef(ref, root = designSystem) {
  if (!ref || !ref.startsWith('#/')) {
    return null;
  }
  
  // Remove the # prefix and split by /
  const path = ref.slice(2).split('/').filter(Boolean);
  
  // Follow the path through the design system
  let current = root;
  for (const segment of path) {
    if (current && typeof current === 'object' && segment in current) {
      current = current[segment];
    } else {
      console.warn(`Warning: Could not resolve reference ${ref} at segment "${segment}"`);
      return null;
    }
  }
  
  return current;
}

// Helper function to get the actual token value (resolving $ref if needed)
function getTokenValue(token) {
  // If token has $ref, resolve it
  if (token.$ref) {
    const resolved = resolveRef(token.$ref);
    if (resolved) {
      // Recursively resolve if the resolved token also has $ref
      if (resolved.$ref) {
        return getTokenValue(resolved);
      }
      return resolved;
    }
  }
  
  // Otherwise return the token itself
  return token;
}

// Helper function to format value based on type
function formatValue(token) {
  // Resolve $ref if present
  const resolvedToken = getTokenValue(token);
  
  const type = resolvedToken.$type;
  const value = resolvedToken.$value;

  if (type === 'color') {
    return value.hex || `rgb(${value.components.map(c => Math.round(c * 255)).join(', ')})`;
  } else if (type === 'number') {
    return `${value}px`;
  } else if (type === 'string') {
    return `'${value}'`;
  }
  return value;
}

// Helper to format font weight (map string names to numeric CSS values)
function formatFontWeight(token) {
  // Resolve $ref if present
  const resolvedToken = getTokenValue(token);
  const value = resolvedToken.$value;
  
  if (fontWeightMap[value] !== undefined) {
    return fontWeightMap[value];
  }
  // If already numeric, return as-is
  if (!isNaN(value)) {
    return value;
  }
  // Fallback: return 400
  return 400;
}

// Process color tokens
css += '\n  /* Colors */\n';
for (const [colorName, colorScale] of Object.entries(designSystem.color || {})) {
  if (typeof colorScale === 'object' && colorScale.$type) {
    // Single color value
    css += `  ${toCSSVar(['color', colorName])}: ${formatValue(colorScale)};\n`;
  } else {
    // Color scale (e.g., blue.0, blue.10, etc.)
    for (const [shade, token] of Object.entries(colorScale)) {
      css += `  ${toCSSVar(['color', colorName, shade])}: ${formatValue(token)};\n`;
    }
  }
}

// Process font tokens
css += '\n  /* Typography - Font Families */\n';
if (designSystem.font?.['font-style']) {
  const fontStyle = designSystem.font['font-style'];
  if (fontStyle.Primary) {
    css += `  ${toCSSVar(['font-family-primary'])}: ${formatValue(fontStyle.Primary)};\n`;
  }
  if (fontStyle.Secondary) {
    css += `  ${toCSSVar(['font-family-secondary'])}: ${formatValue(fontStyle.Secondary)};\n`;
  }
  if (fontStyle.headings) {
    css += `  ${toCSSVar(['font-family-heading'])}: ${formatValue(fontStyle.headings)};\n`;
  }
  if (fontStyle.body) {
    css += `  ${toCSSVar(['font-family-body'])}: ${formatValue(fontStyle.body)};\n`;
  }
  if (fontStyle.label) {
    css += `  ${toCSSVar(['font-family-label'])}: ${formatValue(fontStyle.label)};\n`;
  }
  if (fontStyle.caption) {
    css += `  ${toCSSVar(['font-family-caption'])}: ${formatValue(fontStyle.caption)};\n`;
  }
  if (fontStyle.numbers) {
    css += `  ${toCSSVar(['font-family-numbers'])}: ${formatValue(fontStyle.numbers)};\n`;
  }
}

// Process font sizes
css += '\n  /* Typography - Font Sizes */\n';
if (designSystem.font?.['font-size']) {
  for (const [sizeName, token] of Object.entries(designSystem.font['font-size'])) {
    css += `  ${toCSSVar(['font-size', sizeName])}: ${formatValue(token)};\n`;
  }
}

// Process font weights
css += '\n  /* Typography - Font Weights */\n';
if (designSystem.font?.['font-weight']) {
  for (const [weightName, token] of Object.entries(designSystem.font['font-weight'])) {
    css += `  ${toCSSVar(['font-weight', weightName])}: ${formatFontWeight(token)};\n`;
  }
}

// Process line heights
css += '\n  /* Typography - Line Heights */\n';
if (designSystem.font?.['line-height']) {
  for (const [lhName, token] of Object.entries(designSystem.font['line-height'])) {
    // Resolve $ref if present
    const resolvedToken = getTokenValue(token);
    const value = resolvedToken.$value;
    // Line heights from Figma are absolute pixel values, not multipliers
    css += `  ${toCSSVar(['line-height', lhName])}: ${value}px;\n`;
  }
}

// Process spacing
css += '\n  /* Spacing Scale */\n';
if (designSystem.spacing) {
  for (const [spacingName, token] of Object.entries(designSystem.spacing)) {
    css += `  ${toCSSVar(['spacing', spacingName])}: ${formatValue(token)};\n`;
  }
}

// Process border-radius
css += '\n  /* Border Radius */\n';
if (designSystem['border-radius']) {
  for (const [radiusName, token] of Object.entries(designSystem['border-radius'])) {
    css += `  ${toCSSVar(['radius', radiusName])}: ${formatValue(token)};\n`;
  }
}

// Process semantic text colors
css += '\n  /* Semantic Text Colors */\n';
if (designSystem.text) {
  for (const [textName, token] of Object.entries(designSystem.text)) {
    css += `  ${toCSSVar(['color-text', textName])}: ${formatValue(token)};\n`;
  }
}

// Process semantic surface colors
css += '\n  /* Semantic Surface Colors */\n';
if (designSystem.surface) {
  for (const [surfaceName, token] of Object.entries(designSystem.surface)) {
    const cssName = surfaceName.replace(/-/g, '-');
    css += `  ${toCSSVar(['color-surface', cssName])}: ${formatValue(token)};\n`;
  }
}

// Process semantic icon colors
css += '\n  /* Semantic Icon Colors */\n';
if (designSystem.icon) {
  for (const [iconName, token] of Object.entries(designSystem.icon)) {
    css += `  ${toCSSVar(['color-icon', iconName])}: ${formatValue(token)};\n`;
  }
}

// Process semantic border colors
css += '\n  /* Semantic Border Colors */\n';
if (designSystem.border) {
  for (const [borderName, token] of Object.entries(designSystem.border)) {
    const cssName = borderName.replace(/-/g, '-');
    css += `  ${toCSSVar(['color-border', cssName])}: ${formatValue(token)};\n`;
  }
}

// Process stroke width
css += '\n  /* Stroke Width */\n';
if (designSystem['stroke-width']) {
  for (const [widthName, token] of Object.entries(designSystem['stroke-width'])) {
    css += `  ${toCSSVar(['stroke-width', widthName])}: ${formatValue(token)};\n`;
  }
}

// Process icon size
css += '\n  /* Icon Size */\n';
if (designSystem['icon size']) {
  for (const [sizeName, token] of Object.entries(designSystem['icon size'])) {
    css += `  ${toCSSVar(['icon-size', sizeName])}: ${formatValue(token)};\n`;
  }
}

// Process shadow (emitted raw — composite value, not wrapped in quotes)
css += '\n  /* Shadow / Elevation */\n';
if (designSystem.shadow) {
  for (const [shadowName, token] of Object.entries(designSystem.shadow)) {
    const resolvedToken = getTokenValue(token);
    css += `  ${toCSSVar(['shadow', shadowName])}: ${resolvedToken.$value};\n`;
  }
}

// Add semantic aliases for backward compatibility (if needed)
css += '\n  /* Semantic Color Aliases (for backward compatibility) */\n';
if (designSystem.color?.blue) {
  css += `  ${toCSSVar(['color-background-primary'])}: var(--color-blue-950);\n`;
  css += `  ${toCSSVar(['color-background-secondary'])}: var(--color-blue-900);\n`;
  css += `  ${toCSSVar(['color-background-tertiary'])}: var(--color-blue-800);\n`;
  css += `  ${toCSSVar(['color-text-primary'])}: var(--color-blue-0);\n`;
  css += `  ${toCSSVar(['color-text-secondary'])}: var(--color-blue-200);\n`;
  css += `  ${toCSSVar(['color-text-tertiary'])}: var(--color-blue-400);\n`;
  css += `  ${toCSSVar(['color-border-primary'])}: var(--color-blue-800);\n`;
  css += `  ${toCSSVar(['color-border-secondary'])}: var(--color-blue-700);\n`;
  css += `  ${toCSSVar(['color-accent-primary'])}: var(--color-blue-500);\n`;
  css += `  ${toCSSVar(['color-accent-secondary'])}: var(--color-blue-400);\n`;
  css += `  ${toCSSVar(['color-accent-hover'])}: var(--color-blue-600);\n`;
}

css += '}\n';

// Write to tokens.css
const outputPath = join(rootDir, 'src/styles/tokens.css');
writeFileSync(outputPath, css, 'utf-8');

console.log('✅ Successfully generated tokens.css from design-system.json');
console.log(`📝 Output: ${outputPath}`);
